### ISSUE TITLE
семантика

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/template-portfolio#1]
https://github.com/DenisPitsul/template-portfolio/blob/4157f6b9d3c42d625635ab51bb2d5201ac424821/index.html#L22-L23
- h1 - це не навігаційний елемент. Тут можна було б об'єднати заголовок та nav в header, але винести заголовок з nav

**Comment by pecourses** [comment]
https://github.com/DenisPitsul/template-portfolio/blob/4157f6b9d3c42d625635ab51bb2d5201ac424821/index.html#L85
- схоже на заголовок. Ну і тоді буде логічно ввзяти відповідні підрозділи з заголовками h3 в 3 секції.

**Comment by pecourses** [comment]
- https://github.com/DenisPitsul/template-portfolio/blob/4157f6b9d3c42d625635ab51bb2d5201ac424821/index.html#L108
- важко сказати, що це список (якщо трактувати тут список як набір характеристик). Скоріше, частина елементів є списком, але кнопка точно в список не входе. Заголовок _Basic_ також можна трактувати як заголовок секції з характеристиками тарифного плану. Тому по структурі тут би гарно зайшло
```
section
    h4
    ul
    button
```

**Comment by DenisPitsul** [comment]
Resolved in commits:
https://github.com/DenisPitsul/template-portfolio/commit/536140dc8d81c62e3ae126f9a04884b9b065d353
https://github.com/DenisPitsul/template-portfolio/commit/186e164cf7320f0da94caa9c9a652f5a7325245e
