### ISSUE TITLE
імейл

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/template-portfolio#2]
https://github.com/DenisPitsul/template-portfolio/blob/4157f6b9d3c42d625635ab51bb2d5201ac424821/index.html#L87-L88
-  з точки зору UX це доречно зробити посиланнями з `mailto` та `tel`.

**Comment by DenisPitsul** [comment]
Resolved in commit:
https://github.com/DenisPitsul/template-portfolio/commit/6b6b1ce36f561585de02cabd18a151f368914828

**Comment by pecourses** [comment]
https://github.com/DenisPitsul/template-portfolio/blob/186e164cf7320f0da94caa9c9a652f5a7325245e/index.html#L93
- тут телефон, а не мильник, на автоматі однакові написали
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_phoneto

**Comment by DenisPitsul** [comment]
Fixed in commits:
https://github.com/DenisPitsul/template-portfolio/commit/e6c09b148bef55e04635110d9f339b9a33167908
https://github.com/DenisPitsul/template-portfolio/commit/fd1ae1d37c4f623529280066ef08e1a36a337be8
