### ISSUE TITLE
вкладеність

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/template-portfolio#3]
https://github.com/DenisPitsul/template-portfolio/blob/4157f6b9d3c42d625635ab51bb2d5201ac424821/index.html#L140-L141
- якщо для класів не принципова вкладеність, то краще не навішувати додаткові обгортки, щоб не захаращувати код:
```html
<section class="contact contact-container">
```

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/template-portfolio/commit/fa034420717839e5418dd82abb6104426a07cc2b
